### ISSUE TITLE
How to run locally to check the performance without submission?

### ISSUE THREAD

**Issue by qazmichaelgw** [duckietown/challenge-aido1_LF1#5]
I try to run the built docker image locally to check the whole pipline without submission to avoid waiting for evaluation. But I got the following error when running it:
```
root@e0d08e013c08:/project# python solution.py 
INFO:dts:duckietown-shell 3.0.11
INFO:duckietown-challenges:duckietown-challenges 3.0.22
Starting submission
ERROR:duckietown-challenges:solution:InvalidEnvironment:
Traceback (most recent call last):
  File "/notebooks/src/duckietown-challenges/src/duckietown_challenges/cie_concrete.py", line 426, in wrap_solution
    cis.get_challenge_name()
  File "/notebooks/src/duckietown-challenges/src/duckietown_challenges/cie_concrete.py", line 141, in get_challenge_name
    raise InvalidEnvironment(str(e))
InvalidEnvironment: 'challenge_name'
```

**Comment by AndreaCensi** [comment]
@qazmichaelgw we have implemented this functionality.

Please do:

      $ dts challenge evaluate

to run locally.
